'''
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
'''


# Iterate through the Fibonacci sequence, summing up the even values.
def euler_2(n):
    a, b = 1, 2
    total = 0
    
    # While the first term is less than the limit n...
    while a < n:
        # Add it to the total if it is even.
        if a % 2 == 0:
            total += a
        # Update a and b according to the Fibonacci sequence.
        a, b = b, a + b

    return total

print(euler_2(4000000))