# Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.


# Iterate through the Fibonacci sequence, summing up even values.
euler_2 <- function(n) {
  a <- 1
  b <- 2
  sum <- 0
  # While a is less than the target value...
  while (a < n) {
    # Add a to the sum if it is even.
    if (a %% 2 == 0) {
      sum <- sum + a
    }
    # Update a and b according to the Fibonacci sequence.
    temp <- a
    a <- b
    b <- temp + b
  }
  sum
}

result <- euler_2(4000000)
print(result)
